In [1]:
import numpy as np

In [2]:
print(np.__version__) 

2.1.3


In [4]:
 arr=np.array([[1,2,3],[4,5,6]]) 
print(arr)

[[1 2 3]
 [4 5 6]]


In [13]:
a = np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [14]:
a = np.ones(7)
print(a)

[1. 1. 1. 1. 1. 1. 1.]


In [15]:
a = np.arange(0, 10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [17]:
a = np.arange(0, 12,3)
print(a)

[0 3 6 9]


In [18]:
a = np.array([3,1,2,6,4,5])
print(np.sort(a))


[1 2 3 4 5 6]


In [21]:
a = np.array([11,9,0,5])
print(np.sort(a))

[ 0  5  9 11]


In [34]:
arr = np.array([[1, 2 ,3],[4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [39]:
a = np.array([1,2])
b = np.array([3,4])
print(np.concatenate([a,b]))


[1 2 3 4]


In [40]:
a = np.array([3,4])
b = np.array([2,1])
print(np.concatenate([a,b]))

[3 4 2 1]


In [41]:
a = np.array([3,1,2])
print(np.argsort(a))


[1 2 0]


In [42]:
a = np.array([1,5,2])
print(np.min(a))


1


In [43]:
a = np.array([1,5,2])
print(np.max(a))


5


In [44]:
a = np.array([1,5,2,4])
print(np.mean(a))


3.0


In [45]:
a = np.array([1,5,2,4,7])
print(np.sum(a))


19
